# Pipeline name or workflow name
name: First workflow

# Set trigger
on:
  push:
    branches:
      - main

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Print welcome message
        run: echo "Welcome to GitHub Actions"

      - name: Print hello message
        run: echo "Hello...."